;<?php die('PDBP'); ?>
salt[dtype] = label
used[dtype] = label
used[extra][] = true
usesalt[dtype] = bool
static[dtype] = string
usedyn[dtype] = bool
signs[dtype] = string
dynlen[dtype] = int
dynlen[extra][] = '0'
dynlen[extra][] = 20
restricted[dtype] = array
submit[dtype] = submit
submit[extra] = true