;<?php die('PDBP'); ?>
[smarty]
real_name = "Smarty Template Engine"
description = "Dieses Paket enthällt die Smarty Template engine, welche php Code von der Ausgabe trennt."
patchnotes[] = "2.6.26; Inial release."
version = "2.6.26"
type = "run"
active = "true"
author = "New Digital Group"
mail = 
license = "lgpl"
website = "http://www.smarty.net/"
depend_runtime[] = "hello_world"
[hello_world]
real_name = "Hallo Welt!"
description = "Dieses Paket gibt Hallo Welt aus."
patchnotes[] = "0.1.0; Release Alpha"
patchnotes[] = "0.1.1; Bug gefixt"
version = "0.1.1"
type = "run"
active = "true"
author = "GH1234"
mail = "jonas.schwabe@gmail.com"
license = "gpl"
website = "http://www.cascaded-web.com"
